name: Push to main branch

on:
  push:
    branches:
      - main
jobs:
  ms3_review:
    if: (github.actor != 'ms3-bot' && github.event.pusher.name != 'github-actions[bot]')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout corpus repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.MS3_BOT_TOKEN }}
          path: ${{ github.event.repository.name }}

      - name: Run 'ms3 review' via dcml_corpus_workflow action
        uses: DCMLab/dcml_corpus_workflow@v2.5.4 # Uses an action in the root directory
        id: act_docker
        # working-directory: ${{ github.repository.name }}
        # needs to become a parameter/env variable
        with:
          ms3-command: "push_to_main"
        env:
          Token: "${{ secrets.MS3_BOT_TOKEN }}"
          IsThereAPullRequestOpened: ""
          commitFrom: "${{ github.event.before }}"
          commitTo: ""
          comment_msg: ""
          pr_title: ""
          directory: "${{ github.workspace }}"
          working_dir: ${{ github.event.repository.name }}
